
export const HttpUrl={
  GET_NEWS_TYPE: 'http://**.**.**.**:**/getNewsType',
  GET_NEWS_LIST: 'http://**.**.**.**:**/getNewsList',
}

export const HttpConstant={
  HTTP_CODE_200: 200,
  SERVER_CODE_SUCCESS: 'success',
  HTTP_TIMEOUT: 10000,
}

/**
 * TabBars
 */
export const TabBars={
  DEFAULT_NEWS_TYPES: [{ id: 0, name: '全部' }, { id: 1, name: '国内' }, { id: 2, name: '国际' }, { id: 3, name: '娱乐' },
    { id: 4, name: '军事' }, { id: 5, name: '体育' }, { id: 6, name: '科技' }, { id: 7, name: '财经' },],

}